src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=CustomerRepository::class)
 */
class Customer implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $customerLastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $customerFirstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $customerNickname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $customerEmail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $customerPhoneHome;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $customerCellPhone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $customerCompany;

    /**
     * @ORM\Column(type="bigint", nullable=true)
     */
    private $customerSiretCompany;

    /**
     * @ORM\OneToMany(targetEntity=Address::class, mappedBy="customer")
     */
    private $addresses;

    /**
     * @ORM\ManyToOne(targetEntity=CustomerCategory::class, inversedBy="customers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $customerCategory;

    /**
     * @ORM\OneToMany(targetEntity=Ordered::class, mappedBy="customer")
     */
    private $orders;

    /**
     * @ORM\OneToOne(targetEntity=Artist::class, mappedBy="customer", cascade={"persist", "remove"})
     */
    private $artist;

    public function __construct()
    {
        $this->addresses = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getCustomerLastName(): ?string
    {
        return $this->customerLastName;
    }

    public function setCustomerLastName(string $customerLastName): self
    {
        $this->customerLastName = $customerLastName;

        return $this;
    }

    public function getCustomerFirstName(): ?string
    {
        return $this->customerFirstName;
    }

    public function setCustomerFirstName(string $customerFirstName): self
    {
        $this->customerFirstName = $customerFirstName;

        return $this;
    }

    public function getCustomerNickname(): ?string
    {
        return $this->customerNickname;
    }

    public function setCustomerNickname(string $customerNickname): self
    {
        $this->customerNickname = $customerNickname;

        return $this;
    }

    public function getCustomerEmail(): ?string
    {
        return $this->customerEmail;
    }

    public function setCustomerEmail(string $customerEmail): self
    {
        $this->customerEmail = $customerEmail;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password): void
    {
        $this->password = $password;
    }

    public function getCustomerPhoneHome(): ?string
    {
        return $this->customerPhoneHome;
    }

    public function setCustomerPhoneHome(?string $customerPhoneHome): self
    {
        $this->customerPhoneHome = $customerPhoneHome;

        return $this;
    }

    public function getCustomerCellPhone(): ?string
    {
        return $this->customerCellPhone;
    }

    public function setCustomerCellPhone(string $customerCellPhone): self
    {
        $this->customerCellPhone = $customerCellPhone;

        return $this;
    }

    public function getCustomerCompany(): ?string
    {
        return $this->customerCompany;
    }

    public function setCustomerCompany(?string $customerCompany): self
    {
        $this->customerCompany = $customerCompany;

        return $this;
    }

    public function getCustomerSiretCompany(): ?string
    {
        return $this->customerSiretCompany;
    }

    public function setCustomerSiretCompany(?string $customerSiretCompany): self
    {
        $this->customerSiretCompany = $customerSiretCompany;

        return $this;
    }

    /**
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->setCustomer($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->addresses->contains($address)) {
            $this->addresses->removeElement($address);
            // set the owning side to null (unless already changed)
            if ($address->getCustomer() === $this) {
                $address->setCustomer(null);
            }
        }

        return $this;
    }

    public function getCustomerCategory(): ?CustomerCategory
    {
        return $this->customerCategory;
    }

    public function setCustomerCategory(?CustomerCategory $customerCategory): self
    {
        $this->customerCategory = $customerCategory;

        return $this;
    }

    /**
     * @return Collection|Ordered[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Ordered $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setCustomer($this);
        }

        return $this;
    }

    public function removeOrder(Ordered $order): self
    {
        if ($this->orders->contains($order)) {
            $this->orders->removeElement($order);
            // set the owning side to null (unless already changed)
            if ($order->getCustomer() === $this) {
                $order->setCustomer(null);
            }
        }

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(Artist $artist): self
    {
        $this->artist = $artist;

        // set the owning side of the relation if necessary
        if ($artist->getCustomer() !== $this) {
            $artist->setCustomer($this);
        }

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        return ['ROLE_MEMBER'];
    }

    /**
     * @inheritDoc
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * @inheritDoc
     */
    public function getUsername()
    {
        return $this->customerEmail;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

templates/_static/_footer.html.twig
<footer class="container-fluid">
    <div class="container">

        <div class="col-xs-12">
            <p>
                {% set route_name = app.request.attributes.get('_route') %}
                <a href="{{ url('mentions_legales') }}" {% if route_name == 'mentions_legales' %} class="active_link" {% else %} class=""{% endif %}>{{ "Mentions légales" | trans }}</a>
                |
                <a href="{{ url('cgv') }}" {% if route_name == 'cgv' %} class="active_link" {% else %} class=""{% endif %}>{{ "CGU" | trans }}</a>
                |
                <a href="{{ url('termes-location') }}" {% if route_name == 'termes-location' %} class="active_link" {% else %} class=""{% endif %}>{{ "Termes de location" | trans }}</a>
                |

                <a href="https://nfactory.io/" target="blank">© NFactory School - 2018</a>

            </p>
        </div> <!-- /.col-xs-12-->

        <div class="col-xs-12">
            <p>
                {% trans %}
                Partenaires
                {% endtrans %}
            </p>
        </div>

        <div class="col-xs-12">
            <a href="https://campus-saint-marc.com/" target="blank"><img src="{{ asset('build/footer/foot-csm.png') }}"></a>
            <a href="https://fredericnoel.com/"  target="blank"><img src="{{ asset('build/footer/foot-fredericnoel.png') }}"></a>
            <a href="https://nfactory.io/"  target="blank"><img src="{{ asset('build/footer/foot-nf.png') }}"></a>
            <a href="https://nfactory.io/devenez-developpeur-web-nfactory-school/" target="blank"><img src="{{ asset('build/footer/foot-nfc.png') }}"></a>
            <a href="http://www.wf3.fr/"  target="blank"><img src="{{ asset('build/footer/foot-wf3.png') }}"></a>
        </div>
        <div class="col-xs-12">
            <p>
                Powered by <a href="{{url('nlocart')}}"><img src="{{ asset('build/oeuvres/logo_NLocArt.png') }}" alt="logo NLocArt" id="logo_NLocArt"></a>
            </p>
        </div> <!-- /.col-xs-12-->
    </div> <!-- /.container -->
</footer>

templates/_static/_nav.html.twig
{% set route_name = app.request.attributes.get('_route') %}

<nav class="navbar navbar-expand-md navbar-default fixed-top">
    <div class="container">
        <button class="navbar-toggler toggler-white" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
                <i class="fas fa-bars bg_white text-center"></i>
            </span>
        </button>
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ path('app_index') }}" id="logo_ecloz"><img src="{{ asset('build/oeuvres/logo-ecloz.png') }}" alt="Ecloz"></a>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0 pa-r-70 text-nowrap">
                <li class="nav-item d-inline-block">
                    <a href="{{ url('app_index') }}#artiste" id="lienArtiste" class="nav-link">{{ "L'artiste" | trans }}</a>
                </li>
                <li class="nav-item d-inline-block">
                    <a class="nav-link" href="{{ url('app_catalog') }}" {% if route_name == 'app_index' %} class="active_link" {% else %} class=""{% endif %}>{{ "Le catalogue" | trans }}</a>
                </li>
                <li class="nav-item d-inline-block">
                    <a href="{{ url('app_index') }}#contact" id="lienContact" class="nav-link">{{ "Contact" | trans }}</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
{#                {%  if (app.user is not null and (app.user.roles[0] == 'ROLE_LOUEUR'))  %}#}
                {#                        <li><a {% if active_link == 'administration' %} {{ "class=\"active_link\"" }} {% endif %} href="{{ url('admin_index') }}">Administration</a></li>#}
                {#                    {% endif %}#}

                {#                    {%  if (app.user is not null and (app.user.roles[0] == 'ROLE_MEMBRE'))  %}#}
                {#                        <li><a href="{{ url('security_account') }}" {% if active_link == 'monCompteUser' %} {{ "class=\"active_link\"" }} {% endif %}>Mon  Compte</a></li>#}
                {#                        <li><a href="{{ url('order_selection') }}" {% if active_link == 'panier' %} {{ "class=\"active_link\"" }} {% endif %}>Ma  Sélection</a></li>#}
                {#                    {% endif %}#}

                {%  if is_granted('IS_AUTHENTICATED_FULLY')%}
                    <li class="nav-item d-inline-block"><a class="nav-link text-nowrap" href="{{ path('app_logout') }}">{{ "Déconnexion" | trans }}</a></li>
                {% else %}
                    <li class="nav-item d-inline-block"><a class="nav-link text-nowrap" href="{{ url('app_login') }}" {% if route_name == 'app_index' %} class="active_link" {% else %} class=""{% endif %}>{{ "Se Connecter" | trans }}</a></li>
                    <li class="nav-item d-inline-block"><a class="nav-link text-nowrap" href="{{ url('app_register') }}" {% if route_name == 'app_index' %} class="active_link" {% else %} class=""{% endif %}>{{ "S'inscrire" | trans }}</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>